name: Deploy

on:
  push:
    branches: ["main"]
    # optional nur tags:
    # tags: ["v*"]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Task6/web

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Task6/web/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format-check

      - name: Tests
        run: npm test

  deploy:
    name: build-push-deploy
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (latest)
        uses: docker/build-push-action@v6
        with:
          context: ./Task6/web
          file: ./Task6/web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m324-task6:latest

      - name: Trigger Deploy Hook
        if: ${{ secrets.DEPLOY_HOOK_URL != '' }}
        run: curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"
