name: Deploy

on:
  push:
    branches: [ "main" ]
    # optional nur tags:
    # tags: [ "v*" ]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Task6/web

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: Task6/web/package-lock.json

      - run: npm ci
      - run: npm run lint
      - run: npm run format-check
      - run: npm test

  deploy:
    name: build-push-deploy
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push (latest)
        uses: docker/build-push-action@v6
        with:
          context: ./Task6/web
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/m324-task6:latest

      # Optional: Deploy Hook (z.B. Render)
      - name: Trigger Deploy Hook
        run: curl -X POST "${{ secrets.DEPLOY_HOOK_URL }}"
